---
# nginx
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen      : "80"
    server_name : "localhost"
    root        : "html"
    return      : "301 https://$host$request_uri"

  - listen: "443"
    server_name: "{{ refwd_hostname }}"
    root: "html"
    access_log: "/var/log/nginx/re-fwd.access.log"
    extra_parameters: |
      # ssl
      ssl_certificate          /etc/ssl/certs/{{ refwd_ssl_cert }};
      ssl_certificate_key      /etc/ssl/private/{{ refwd_ssl_key }};
      ssl on;
      location / {
        # Fix error (failed: Error during WebSocket handshake: Unexpected response code: 400)
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "upgrade";
        # Keep the ip address accessible
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        # Fix the “It appears that your reverse proxy set up is broken" error.
        proxy_pass          http://load_balancer80;
        proxy_read_timeout  90;
        proxy_redirect      http://load_balancer80 https://{{ refwd_hostname }};
      }
      # ssl_session_cache  builtin:1000  shared:SSL:10m;
      ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
      ssl_prefer_server_ciphers on

  - listen: "8443"
    server_name: "{{ refwd_hostname }}"
    root: "html"
    access_log: "/var/log/nginx/chatsocket.access.log"
    extra_parameters: |
      # ssl
      ssl_certificate          /etc/ssl/certs/{{ refwd_ssl_cert }};
      ssl_certificate_key      /etc/ssl/private/{{ refwd_ssl_key }};
      ssl on;
      location / {
        # Fix error (failed: Error during WebSocket handshake: Unexpected response code: 400)
        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "upgrade";
        # Keep the ip address accessible
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        # Fix the “It appears that your reverse proxy set up is broken" error.
        proxy_pass          http://load_balancer8443;
        proxy_read_timeout  90;
        proxy_redirect      http://load_balancer8443 https://{{ refwd_hostname }};
      }
      # ssl_session_cache  builtin:1000  shared:SSL:10m;
      ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
      ssl_prefer_server_ciphers on

nginx_upstreams:
  - { name: load_balancer80,   servers: { "127.0.0.1:40080" } }
  - { name: load_balancer8443, servers: { "127.0.0.1:48443" } }
